version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rash_pulse_rabbitmq
    ports:
      - "5672:5672"   # Code is port se RabbitMQ se baat karega
      - "15672:15672" # Is port se hum browser mein dashboard dekhenge
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rash_pulse_network

volumes:
  rabbitmq_data:

networks:
  rash_pulse_network:
    driver: bridge